import Scorecard from "../src/components/Containers/Scorecard";

export const game_details = [
    {
        "GameID": 61443,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "Final",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T13:10:00",
        "AwayTeam": "MIA",
        "HomeTeam": "NYM",
        "AwayTeamID": 22,
        "HomeTeamID": 18,
        "RescheduledGameID": null,
        "StadiumID": 8,
        "Channel": "SNY,FSFL",
        "Inning": 9,
        "InningHalf": "B",
        "AwayTeamRuns": 0,
        "HomeTeamRuns": 1,
        "AwayTeamHits": 1,
        "HomeTeamHits": 2,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": 10005753,
        "LosingPitcherID": 10001435,
        "SavingPitcherID": null,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10006508,
        "HomeTeamProbablePitcherID": 10001077,
        "Outs": null,
        "Balls": null,
        "Strikes": null,
        "CurrentPitcherID": null,
        "CurrentHitterID": null,
        "AwayTeamStartingPitcherID": 10006508,
        "HomeTeamStartingPitcherID": 10001077,
        "CurrentPitchingTeamID": null,
        "CurrentHittingTeamID": null,
        "PointSpread": -0.7,
        "OverUnder": 1.8,
        "AwayTeamMoneyLine": 78,
        "HomeTeamMoneyLine": -92,
        "ForecastTempLow": 25,
        "ForecastTempHigh": 26,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": 26,
        "ForecastWindSpeed": 2,
        "ForecastWindDirection": 73,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": null,
        "RunnerOnSecond": null,
        "RunnerOnThird": null,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": null,
        "DueUpHitterID2": null,
        "DueUpHitterID3": null,
        "GlobalGameID": 10061443,
        "GlobalAwayTeamID": 10000022,
        "GlobalHomeTeamID": 10000018,
        "PointSpreadAwayTeamMoneyLine": -60,
        "PointSpreadHomeTeamMoneyLine": 49,
        "LastPlay": "Scrambled",
        "IsClosed": true,
        "Updated": "2021-04-08T20:44:32",
        "GameEndDateTime": "2021-04-08T16:32:14",
        "HomeRotationNumber": 419,
        "AwayRotationNumber": 419,
        "NeutralVenue": false,
        "InningDescription": null,
        "OverPayout": -52,
        "UnderPayout": -50,
        "Innings": [
            {
                "InningID": 390749,
                "GameID": 61443,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390751,
                "GameID": 61443,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390752,
                "GameID": 61443,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390754,
                "GameID": 61443,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390756,
                "GameID": 61443,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390758,
                "GameID": 61443,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390763,
                "GameID": 61443,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390767,
                "GameID": 61443,
                "InningNumber": 8,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390772,
                "GameID": 61443,
                "InningNumber": 9,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            }
        ]
    },
    {
        "GameID": 61447,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "Final",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T13:35:00",
        "AwayTeam": "CHC",
        "HomeTeam": "PIT",
        "AwayTeamID": 9,
        "HomeTeamID": 4,
        "RescheduledGameID": null,
        "StadiumID": 29,
        "Channel": "ATPT",
        "Inning": 9,
        "InningHalf": "B",
        "AwayTeamRuns": 1,
        "HomeTeamRuns": 0,
        "AwayTeamHits": 2,
        "HomeTeamHits": 2,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": 10000184,
        "LosingPitcherID": 10000364,
        "SavingPitcherID": 10000058,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10000184,
        "HomeTeamProbablePitcherID": 10000364,
        "Outs": null,
        "Balls": null,
        "Strikes": null,
        "CurrentPitcherID": null,
        "CurrentHitterID": null,
        "AwayTeamStartingPitcherID": 10000184,
        "HomeTeamStartingPitcherID": 10000364,
        "CurrentPitchingTeamID": null,
        "CurrentHittingTeamID": null,
        "PointSpread": 0.3,
        "OverUnder": 1.8,
        "AwayTeamMoneyLine": -70,
        "HomeTeamMoneyLine": 60,
        "ForecastTempLow": 28,
        "ForecastTempHigh": 29,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": 29,
        "ForecastWindSpeed": 2,
        "ForecastWindDirection": 63,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": null,
        "RunnerOnSecond": null,
        "RunnerOnThird": null,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": null,
        "DueUpHitterID2": null,
        "DueUpHitterID3": null,
        "GlobalGameID": 10061447,
        "GlobalAwayTeamID": 10000009,
        "GlobalHomeTeamID": 10000004,
        "PointSpreadAwayTeamMoneyLine": 49,
        "PointSpreadHomeTeamMoneyLine": -60,
        "LastPlay": "Scrambled",
        "IsClosed": true,
        "Updated": "2021-04-08T20:44:34",
        "GameEndDateTime": "2021-04-08T16:53:54",
        "HomeRotationNumber": 420,
        "AwayRotationNumber": 420,
        "NeutralVenue": false,
        "InningDescription": null,
        "OverPayout": -49,
        "UnderPayout": -54,
        "Innings": [
            {
                "InningID": 390750,
                "GameID": 61447,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390753,
                "GameID": 61447,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390755,
                "GameID": 61447,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390757,
                "GameID": 61447,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390759,
                "GameID": 61447,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390762,
                "GameID": 61447,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390766,
                "GameID": 61447,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390771,
                "GameID": 61447,
                "InningNumber": 8,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390780,
                "GameID": 61447,
                "InningNumber": 9,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            }
        ]
    },
    {
        "GameID": 61441,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "Final",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T15:05:00",
        "AwayTeam": "BOS",
        "HomeTeam": "BAL",
        "AwayTeamID": 25,
        "HomeTeamID": 19,
        "RescheduledGameID": null,
        "StadiumID": 22,
        "Channel": "MASN,NESN",
        "Inning": 9,
        "InningHalf": "B",
        "AwayTeamRuns": 2,
        "HomeTeamRuns": 1,
        "AwayTeamHits": 3,
        "HomeTeamHits": 1,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": 10000155,
        "LosingPitcherID": 10000794,
        "SavingPitcherID": null,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10000155,
        "HomeTeamProbablePitcherID": 10000794,
        "Outs": null,
        "Balls": null,
        "Strikes": null,
        "CurrentPitcherID": null,
        "CurrentHitterID": null,
        "AwayTeamStartingPitcherID": 10000155,
        "HomeTeamStartingPitcherID": 10000794,
        "CurrentPitchingTeamID": null,
        "CurrentHittingTeamID": null,
        "PointSpread": 0.3,
        "OverUnder": 1.9,
        "AwayTeamMoneyLine": -73,
        "HomeTeamMoneyLine": 63,
        "ForecastTempLow": 25,
        "ForecastTempHigh": 27,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": 27,
        "ForecastWindSpeed": 2,
        "ForecastWindDirection": 65,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": null,
        "RunnerOnSecond": null,
        "RunnerOnThird": null,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": null,
        "DueUpHitterID2": null,
        "DueUpHitterID3": null,
        "GlobalGameID": 10061441,
        "GlobalAwayTeamID": 10000025,
        "GlobalHomeTeamID": 10000019,
        "PointSpreadAwayTeamMoneyLine": 47,
        "PointSpreadHomeTeamMoneyLine": -57,
        "LastPlay": "Scrambled",
        "IsClosed": true,
        "Updated": "2021-04-08T20:44:30",
        "GameEndDateTime": "2021-04-08T18:19:27",
        "HomeRotationNumber": 423,
        "AwayRotationNumber": 423,
        "NeutralVenue": false,
        "InningDescription": null,
        "OverPayout": -53,
        "UnderPayout": -50,
        "Innings": [
            {
                "InningID": 390760,
                "GameID": 61441,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390765,
                "GameID": 61441,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390768,
                "GameID": 61441,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390773,
                "GameID": 61441,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390778,
                "GameID": 61441,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390781,
                "GameID": 61441,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390786,
                "GameID": 61441,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390791,
                "GameID": 61441,
                "InningNumber": 8,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390795,
                "GameID": 61441,
                "InningNumber": 9,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            }
        ]
    },
    {
        "GameID": 61440,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "Final",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T15:10:00",
        "AwayTeam": "ARI",
        "HomeTeam": "COL",
        "AwayTeamID": 14,
        "HomeTeamID": 23,
        "RescheduledGameID": null,
        "StadiumID": 44,
        "Channel": "ATRM,FSAZ",
        "Inning": 9,
        "InningHalf": "T",
        "AwayTeamRuns": 1,
        "HomeTeamRuns": 2,
        "AwayTeamHits": 1,
        "HomeTeamHits": 2,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": 10002058,
        "LosingPitcherID": 10009589,
        "SavingPitcherID": 10001692,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10009589,
        "HomeTeamProbablePitcherID": 10002058,
        "Outs": null,
        "Balls": null,
        "Strikes": null,
        "CurrentPitcherID": null,
        "CurrentHitterID": null,
        "AwayTeamStartingPitcherID": 10009589,
        "HomeTeamStartingPitcherID": 10002058,
        "CurrentPitchingTeamID": null,
        "CurrentHittingTeamID": null,
        "PointSpread": -0.7,
        "OverUnder": 2.4,
        "AwayTeamMoneyLine": 49,
        "HomeTeamMoneyLine": -58,
        "ForecastTempLow": 28,
        "ForecastTempHigh": 30,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": 30,
        "ForecastWindSpeed": 0,
        "ForecastWindDirection": 124,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": null,
        "RunnerOnSecond": null,
        "RunnerOnThird": null,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": null,
        "DueUpHitterID2": null,
        "DueUpHitterID3": null,
        "GlobalGameID": 10061440,
        "GlobalAwayTeamID": 10000014,
        "GlobalHomeTeamID": 10000023,
        "PointSpreadAwayTeamMoneyLine": -86,
        "PointSpreadHomeTeamMoneyLine": 70,
        "LastPlay": "Scrambled",
        "IsClosed": true,
        "Updated": "2021-04-08T20:44:30",
        "GameEndDateTime": "2021-04-08T18:04:16",
        "HomeRotationNumber": 421,
        "AwayRotationNumber": 421,
        "NeutralVenue": false,
        "InningDescription": null,
        "OverPayout": -51,
        "UnderPayout": -52,
        "Innings": [
            {
                "InningID": 390761,
                "GameID": 61440,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 1
            },
            {
                "InningID": 390764,
                "GameID": 61440,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390769,
                "GameID": 61440,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390774,
                "GameID": 61440,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390777,
                "GameID": 61440,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390782,
                "GameID": 61440,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 1
            },
            {
                "InningID": 390785,
                "GameID": 61440,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390790,
                "GameID": 61440,
                "InningNumber": 8,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390792,
                "GameID": 61440,
                "InningNumber": 9,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": null
            }
        ]
    },
    {
        "GameID": 61442,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "Final",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T16:10:00",
        "AwayTeam": "KC",
        "HomeTeam": "CHW",
        "AwayTeamID": 5,
        "HomeTeamID": 16,
        "RescheduledGameID": null,
        "StadiumID": 25,
        "Channel": "CSCh",
        "Inning": 9,
        "InningHalf": "T",
        "AwayTeamRuns": 0,
        "HomeTeamRuns": 1,
        "AwayTeamHits": 1,
        "HomeTeamHits": 2,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": 10001154,
        "LosingPitcherID": 10005970,
        "SavingPitcherID": null,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10005970,
        "HomeTeamProbablePitcherID": 10001154,
        "Outs": null,
        "Balls": null,
        "Strikes": null,
        "CurrentPitcherID": null,
        "CurrentHitterID": null,
        "AwayTeamStartingPitcherID": 10005970,
        "HomeTeamStartingPitcherID": 10001154,
        "CurrentPitchingTeamID": null,
        "CurrentHittingTeamID": null,
        "PointSpread": -0.7,
        "OverUnder": 1.7,
        "AwayTeamMoneyLine": 69,
        "HomeTeamMoneyLine": -83,
        "ForecastTempLow": 24,
        "ForecastTempHigh": 24,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": 24,
        "ForecastWindSpeed": 2,
        "ForecastWindDirection": 89,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": null,
        "RunnerOnSecond": null,
        "RunnerOnThird": null,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": null,
        "DueUpHitterID2": null,
        "DueUpHitterID3": null,
        "GlobalGameID": 10061442,
        "GlobalAwayTeamID": 10000005,
        "GlobalHomeTeamID": 10000016,
        "PointSpreadAwayTeamMoneyLine": -66,
        "PointSpreadHomeTeamMoneyLine": 55,
        "LastPlay": "Scrambled",
        "IsClosed": true,
        "Updated": "2021-04-08T21:18:43",
        "GameEndDateTime": "2021-04-08T21:13:36",
        "HomeRotationNumber": 425,
        "AwayRotationNumber": 425,
        "NeutralVenue": false,
        "InningDescription": null,
        "OverPayout": -53,
        "UnderPayout": -50,
        "Innings": [
            {
                "InningID": 390770,
                "GameID": 61442,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 1
            },
            {
                "InningID": 390799,
                "GameID": 61442,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390801,
                "GameID": 61442,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390805,
                "GameID": 61442,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390808,
                "GameID": 61442,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390810,
                "GameID": 61442,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390816,
                "GameID": 61442,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390819,
                "GameID": 61442,
                "InningNumber": 8,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390821,
                "GameID": 61442,
                "InningNumber": 9,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": null
            }
        ]
    },
    {
        "GameID": 61446,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "Final",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T16:10:00",
        "AwayTeam": "SEA",
        "HomeTeam": "MIN",
        "AwayTeamID": 13,
        "HomeTeamID": 20,
        "RescheduledGameID": null,
        "StadiumID": 14,
        "Channel": "RTNW",
        "Inning": 9,
        "InningHalf": "T",
        "AwayTeamRuns": 0,
        "HomeTeamRuns": 2,
        "AwayTeamHits": 2,
        "HomeTeamHits": 3,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": 10001993,
        "LosingPitcherID": 10003325,
        "SavingPitcherID": null,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10003325,
        "HomeTeamProbablePitcherID": 10001993,
        "Outs": null,
        "Balls": null,
        "Strikes": null,
        "CurrentPitcherID": null,
        "CurrentHitterID": null,
        "AwayTeamStartingPitcherID": 10003325,
        "HomeTeamStartingPitcherID": 10001993,
        "CurrentPitchingTeamID": null,
        "CurrentHittingTeamID": null,
        "PointSpread": -0.7,
        "OverUnder": 1.7,
        "AwayTeamMoneyLine": 80,
        "HomeTeamMoneyLine": -97,
        "ForecastTempLow": 26,
        "ForecastTempHigh": 26,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": 26,
        "ForecastWindSpeed": 1,
        "ForecastWindDirection": 74,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": null,
        "RunnerOnSecond": null,
        "RunnerOnThird": null,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": null,
        "DueUpHitterID2": null,
        "DueUpHitterID3": null,
        "GlobalGameID": 10061446,
        "GlobalAwayTeamID": 10000013,
        "GlobalHomeTeamID": 10000020,
        "PointSpreadAwayTeamMoneyLine": -53,
        "PointSpreadHomeTeamMoneyLine": -49,
        "LastPlay": "Scrambled",
        "IsClosed": true,
        "Updated": "2021-04-08T20:44:33",
        "GameEndDateTime": "2021-04-08T20:00:33",
        "HomeRotationNumber": 424,
        "AwayRotationNumber": 424,
        "NeutralVenue": false,
        "InningDescription": null,
        "OverPayout": -51,
        "UnderPayout": -52,
        "Innings": [
            {
                "InningID": 390775,
                "GameID": 61446,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390779,
                "GameID": 61446,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390784,
                "GameID": 61446,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 1
            },
            {
                "InningID": 390788,
                "GameID": 61446,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390794,
                "GameID": 61446,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 1
            },
            {
                "InningID": 390798,
                "GameID": 61446,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390802,
                "GameID": 61446,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390806,
                "GameID": 61446,
                "InningNumber": 8,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390809,
                "GameID": 61446,
                "InningNumber": 9,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": null
            }
        ]
    },
    {
        "GameID": 61444,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "Final",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T16:15:00",
        "AwayTeam": "MIL",
        "HomeTeam": "STL",
        "AwayTeamID": 32,
        "HomeTeamID": 31,
        "RescheduledGameID": null,
        "StadiumID": 41,
        "Channel": null,
        "Inning": 9,
        "InningHalf": "T",
        "AwayTeamRuns": 0,
        "HomeTeamRuns": 1,
        "AwayTeamHits": 1,
        "HomeTeamHits": 1,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": 10007380,
        "LosingPitcherID": 10008425,
        "SavingPitcherID": 10006610,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10007058,
        "HomeTeamProbablePitcherID": 10001162,
        "Outs": null,
        "Balls": null,
        "Strikes": null,
        "CurrentPitcherID": null,
        "CurrentHitterID": null,
        "AwayTeamStartingPitcherID": 10007058,
        "HomeTeamStartingPitcherID": 10001162,
        "CurrentPitchingTeamID": null,
        "CurrentHittingTeamID": null,
        "PointSpread": 0.3,
        "OverUnder": 1.5,
        "AwayTeamMoneyLine": -69,
        "HomeTeamMoneyLine": 58,
        "ForecastTempLow": 24,
        "ForecastTempHigh": 24,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": 24,
        "ForecastWindSpeed": 2,
        "ForecastWindDirection": 93,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": null,
        "RunnerOnSecond": null,
        "RunnerOnThird": null,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": null,
        "DueUpHitterID2": null,
        "DueUpHitterID3": null,
        "GlobalGameID": 10061444,
        "GlobalAwayTeamID": 10000032,
        "GlobalHomeTeamID": 10000031,
        "PointSpreadAwayTeamMoneyLine": 54,
        "PointSpreadHomeTeamMoneyLine": -66,
        "LastPlay": "Scrambled",
        "IsClosed": true,
        "Updated": "2021-04-08T20:44:32",
        "GameEndDateTime": "2021-04-08T19:27:20",
        "HomeRotationNumber": 422,
        "AwayRotationNumber": 422,
        "NeutralVenue": false,
        "InningDescription": null,
        "OverPayout": -56,
        "UnderPayout": 46,
        "Innings": [
            {
                "InningID": 390776,
                "GameID": 61444,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390783,
                "GameID": 61444,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390787,
                "GameID": 61444,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390789,
                "GameID": 61444,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390793,
                "GameID": 61444,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390796,
                "GameID": 61444,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390797,
                "GameID": 61444,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390800,
                "GameID": 61444,
                "InningNumber": 8,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390804,
                "GameID": 61444,
                "InningNumber": 9,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": null
            }
        ]
    },
    {
        "GameID": 61439,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "InProgress",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T19:07:00",
        "AwayTeam": "LAA",
        "HomeTeam": "TOR",
        "AwayTeamID": 21,
        "HomeTeamID": 3,
        "RescheduledGameID": null,
        "StadiumID": 90,
        "Channel": "RSN",
        "Inning": 10,
        "InningHalf": "T",
        "AwayTeamRuns": 1,
        "HomeTeamRuns": 1,
        "AwayTeamHits": 2,
        "HomeTeamHits": 2,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": null,
        "LosingPitcherID": null,
        "SavingPitcherID": null,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10008338,
        "HomeTeamProbablePitcherID": 10005290,
        "Outs": 2,
        "Balls": 0,
        "Strikes": 2,
        "CurrentPitcherID": 10008530,
        "CurrentHitterID": 10008984,
        "AwayTeamStartingPitcherID": 10008338,
        "HomeTeamStartingPitcherID": 10005290,
        "CurrentPitchingTeamID": 21,
        "CurrentHittingTeamID": null,
        "PointSpread": 0.3,
        "OverUnder": 2.2,
        "AwayTeamMoneyLine": -50,
        "HomeTeamMoneyLine": -51,
        "ForecastTempLow": null,
        "ForecastTempHigh": null,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": null,
        "ForecastWindSpeed": null,
        "ForecastWindDirection": null,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": false,
        "RunnerOnSecond": false,
        "RunnerOnThird": true,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": 4653098,
        "DueUpHitterID2": 4650205,
        "DueUpHitterID3": 4650357,
        "GlobalGameID": 10061439,
        "GlobalAwayTeamID": 10000021,
        "GlobalHomeTeamID": 10000003,
        "PointSpreadAwayTeamMoneyLine": 69,
        "PointSpreadHomeTeamMoneyLine": -84,
        "LastPlay": "Scrambled",
        "IsClosed": false,
        "Updated": "2021-04-08T22:25:14",
        "GameEndDateTime": null,
        "HomeRotationNumber": 426,
        "AwayRotationNumber": 425,
        "NeutralVenue": false,
        "InningDescription": "End 9",
        "OverPayout": -52,
        "UnderPayout": -51,
        "Innings": [
            {
                "InningID": 390803,
                "GameID": 61439,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 1
            },
            {
                "InningID": 390807,
                "GameID": 61439,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390811,
                "GameID": 61439,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390813,
                "GameID": 61439,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390814,
                "GameID": 61439,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390817,
                "GameID": 61439,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390822,
                "GameID": 61439,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390824,
                "GameID": 61439,
                "InningNumber": 8,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390826,
                "GameID": 61439,
                "InningNumber": 9,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390828,
                "GameID": 61439,
                "InningNumber": 10,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": null
            }
        ]
    },
    {
        "GameID": 61445,
        "Season": 2021,
        "SeasonType": 1,
        "Status": "InProgress",
        "Day": "2021-04-08T00:00:00",
        "DateTime": "2021-04-08T20:10:00",
        "AwayTeam": "OAK",
        "HomeTeam": "HOU",
        "AwayTeamID": 24,
        "HomeTeamID": 30,
        "RescheduledGameID": null,
        "StadiumID": 63,
        "Channel": "ATSW,CSCA",
        "Inning": 7,
        "InningHalf": "B",
        "AwayTeamRuns": 0,
        "HomeTeamRuns": 1,
        "AwayTeamHits": 1,
        "HomeTeamHits": 2,
        "AwayTeamErrors": 0,
        "HomeTeamErrors": 0,
        "WinningPitcherID": null,
        "LosingPitcherID": null,
        "SavingPitcherID": null,
        "Attendance": null,
        "AwayTeamProbablePitcherID": 10008483,
        "HomeTeamProbablePitcherID": 10007231,
        "Outs": 0,
        "Balls": 0,
        "Strikes": 0,
        "CurrentPitcherID": 10001828,
        "CurrentHitterID": 10000485,
        "AwayTeamStartingPitcherID": 10008483,
        "HomeTeamStartingPitcherID": 10007231,
        "CurrentPitchingTeamID": 30,
        "CurrentHittingTeamID": 24,
        "PointSpread": -0.7,
        "OverUnder": 2.2,
        "AwayTeamMoneyLine": 65,
        "HomeTeamMoneyLine": -77,
        "ForecastTempLow": 33,
        "ForecastTempHigh": 35,
        "ForecastDescription": "Scrambled",
        "ForecastWindChill": 35,
        "ForecastWindSpeed": 3,
        "ForecastWindDirection": 70,
        "RescheduledFromGameID": null,
        "RunnerOnFirst": false,
        "RunnerOnSecond": false,
        "RunnerOnThird": false,
        "AwayTeamStartingPitcher": "Scrambled",
        "HomeTeamStartingPitcher": "Scrambled",
        "CurrentPitcher": "Scrambled",
        "CurrentHitter": "Scrambled",
        "WinningPitcher": "Scrambled",
        "LosingPitcher": "Scrambled",
        "SavingPitcher": "Scrambled",
        "DueUpHitterID1": 4650226,
        "DueUpHitterID2": 4650166,
        "DueUpHitterID3": 4652599,
        "GlobalGameID": 10061445,
        "GlobalAwayTeamID": 10000024,
        "GlobalHomeTeamID": 10000030,
        "PointSpreadAwayTeamMoneyLine": -64,
        "PointSpreadHomeTeamMoneyLine": 52,
        "LastPlay": "Scrambled",
        "IsClosed": false,
        "Updated": "2021-04-08T22:26:02",
        "GameEndDateTime": null,
        "HomeRotationNumber": 427,
        "AwayRotationNumber": 426,
        "NeutralVenue": false,
        "InningDescription": "Mid 7",
        "OverPayout": -52,
        "UnderPayout": -51,
        "Innings": [
            {
                "InningID": 390812,
                "GameID": 61445,
                "InningNumber": 1,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390815,
                "GameID": 61445,
                "InningNumber": 2,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390818,
                "GameID": 61445,
                "InningNumber": 3,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390820,
                "GameID": 61445,
                "InningNumber": 4,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390823,
                "GameID": 61445,
                "InningNumber": 5,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            },
            {
                "InningID": 390825,
                "GameID": 61445,
                "InningNumber": 6,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 1
            },
            {
                "InningID": 390827,
                "GameID": 61445,
                "InningNumber": 7,
                "AwayTeamRuns": 0,
                "HomeTeamRuns": 0
            }
        ]
    }
]

export const games = game_details.map((game_detail) => (
    <Scorecard game={game_detail}/>
  ));