import Scorecard from "../src/components/Containers/Scorecard";

export const game_details = [

    {
        "AwayTeam": "MIL",
        "HomeTeam": "CHC",
        "AwayTeamHits": "2",
        "HomeTeamHits": "5",
        "DateTime": "Today 1:10 PM",
        "InningHalf": "T",
        "Inning": "5",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "OAK",
        "HomeTeam": "BAL",
        "AwayTeamHits": "3",
        "HomeTeamHits": "1",
        "DateTime": "Today 6:05 PM",
        "InningHalf": "",
        "Inning": "",
        "Status": "Final",
    },
    {
        "AwayTeam": "SEA",
        "HomeTeam": "BOS",
        "AwayTeamHits": "2",
        "HomeTeamHits": "3",
        "DateTime": "Today 6:10 PM",
        "InningHalf": "",
        "Inning": "",
        "Status": "Final",
    },
    {
        "AwayTeam": "WSH",
        "HomeTeam": "NYM",
        "AwayTeamHits": "0",
        "HomeTeamHits": "5",
        "DateTime": "Today 6:10 PM",
        "InningHalf": "B",
        "Inning": "9",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "TOR",
        "HomeTeam": "TB",
        "AwayTeamHits": "3",
        "HomeTeamHits": "1",
        "DateTime": "Today 6:10 PM",
        "InningHalf": "T",
        "Inning": "8",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "NYY",
        "HomeTeam": "CLE",
        "AwayTeamHits": "2",
        "HomeTeamHits": "0",
        "DateTime": "Today 6:10 PM",
        "InningHalf": "B",
        "Inning": "6",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "KC",
        "HomeTeam": "DET",
        "AwayTeamHits": "3",
        "HomeTeamHits": "6",
        "DateTime": "Today 6:10 PM",
        "InningHalf": "T",
        "Inning": "7",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "ARI",
        "HomeTeam": "ATL",
        "AwayTeamHits": "2",
        "HomeTeamHits": "2",
        "DateTime": "Today 6:20 PM",
        "InningHalf": "B",
        "Inning": "7",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "TEX",
        "HomeTeam": "CHW",
        "AwayTeamHits": "1",
        "HomeTeamHits": "5",
        "DateTime": "Today 7:10 PM",
        "InningHalf": "T",
        "Inning": "5",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "LAA",
        "HomeTeam": "HOU",
        "AwayTeamHits": "15",
        "HomeTeamHits": "0",
        "DateTime": "Today 7:10 PM",
        "InningHalf": "",
        "Inning": "",
        "Status": "Final",
    },
    {
        "AwayTeam": "PIT",
        "HomeTeam": "MIN",
        "AwayTeamHits": "1",
        "HomeTeamHits": "4",
        "DateTime": "Today 7:10 PM",
        "InningHalf": "T",
        "Inning": "7",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "CIN",
        "HomeTeam": "STL",
        "AwayTeamHits": "0",
        "HomeTeamHits": "1",
        "DateTime": "Today 7:15 PM",
        "InningHalf": "",
        "Inning": "",
        "Status": "Final",
    },
    {
        "AwayTeam": "PHI",
        "HomeTeam": "COL",
        "AwayTeamHits": "2",
        "HomeTeamHits": "9",
        "DateTime": "Today 7:40 PM",
        "InningHalf": "B",
        "Inning": "4",
        "Status": "InProgress",
    },
    {
        "AwayTeam": "MIA",
        "HomeTeam": "SF",
        "AwayTeamHits": "7",
        "HomeTeamHits": "0",
        "DateTime": "Today 8:45 PM",
        "InningHalf": "B",
        "Inning": "3",
        "Status": "InProgress",
    },
     {
        "AwayTeam": "SD",
        "HomeTeam": "LAD",
        "AwayTeamHits": "0",
        "HomeTeamHits": "10",
        "DateTime": "Today 9:10 PM",
        "InningHalf": "B",
        "Inning": "2",
        "Status": "InProgress",
    },
]

export const games = game_details.map((game_detail) => (
    <Scorecard game={game_detail}/>
  ));