from app.models import db, User


def seed_player_users():

    players = [
        {
            "first_name": "Clayton",
            "last_name": "Kershaw",
            "username": "kersh22",
            "email": "kersh22@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Cody",
            "last_name": "Bellinger",
            "username": "belli35",
            "email": "belli35@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Rich",
            "last_name": "Hill",
            "username": "dmountain44",
            "email": "dmountain44@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Joe",
            "last_name": "Kelly",
            "username": "niceswing17",
            "email": "niceswing17@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Kenley",
            "last_name": "Jansen",
            "username": "kenleyfornia",
            "email": "kenleyfornia74@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Dustin",
            "last_name": "May",
            "username": "bigred85",
            "email": "bigred85@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Max",
            "last_name": "Muncy",
            "username": "funkymuncy",
            "email": "funkymuncy13@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Joc",
            "last_name": "Pederson",
            "username": "joctoberking",
            "email": "joctoberking31@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "A.J.",
            "last_name": "Pollock",
            "username": "pollo11",
            "email": "pollo11@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Hyun-Jin",
            "last_name": "Ryu",
            "username": "monster99",
            "email": "monster99@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Chase",
            "last_name": "Utley",
            "username": "silverfox26",
            "email": "silverfox26@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Ross",
            "last_name": "Stripling",
            "username": "chickenstrip",
            "email": "chickenstrip68@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Yasiel",
            "last_name": "Puig",
            "username": "wildhorse66",
            "email": "wildhorse66@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Yasmani",
            "last_name": "Grandal",
            "username": "yasmaniandevil",
            "email": "yasmaniandevil9@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Walker",
            "last_name": "Buehler",
            "username": "buetane21",
            "email": "buetane21@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "David",
            "last_name": "Freese",
            "username": "davehuman",
            "email": "davehuman23@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Matt",
            "last_name": "Beaty",
            "username": "baterstaters",
            "email": "baterstaters45@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Pedro",
            "last_name": "Baez",
            "username": "lamula52",
            "email": "lamula52@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Yimi",
            "last_name": "Garcia",
            "username": "villatrina63",
            "email": "villatrina63@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Tony",
            "last_name": "Gonsolin",
            "username": "GOOOOSE",
            "email": "goooose26@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Enrique",
            "last_name": "Hernandez",
            "username": "kike14",
            "email": "kike14@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Adam",
            "last_name": "Kolarek",
            "username": "ak56D",
            "email": "ak56@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Russell",
            "last_name": "Martin",
            "username": "lemuscle55",
            "email": "lemuscle55@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Kristopher",
            "last_name": "Negron",
            "username": "negronjames",
            "email": "negronjames9@gmail.com",
            "password": "password",
        },
        {
            "first_name": "Casey",
            "last_name": "Sadler",
            "username": "sads65",
            "email": "sads65@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Corey",
            "last_name": "Seager",
            "username": "seags",
            "email": "seags5@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Will",
            "last_name": "Smith",
            "username": "freshprinceofla",
            "email": "smitty16@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Chris",
            "last_name": "Taylor",
            "username": "ct3dodger",
            "email": "ct3dodger@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Justin",
            "last_name": "Turner",
            "username": "redturn2",
            "email": "redturn2@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Alex",
            "last_name": "Verdugo",
            "username": "dugie27",
            "email": "dugie27@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Tyler",
            "last_name": "White",
            "username": "whitey28",
            "email": "whitey28@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Scott",
            "last_name": "Alexander",
            "username": "scott75",
            "email": "scott75@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Caleb",
            "last_name": "Ferguson",
            "username": "ferguson64",
            "email": "ferguson64@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Victor",
            "last_name": "Gonzalez",
            "username": "gonzalez81",
            "email": "gonzalez81@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Brusdar",
            "last_name": "Graterol",
            "username": "graterol48",
            "email": "graterol48@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Corey",
            "last_name": "Knebel",
            "username": "knebel46",
            "email": "knebel46@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Jimmy",
            "last_name": "Nelson",
            "username": "nelson40",
            "email": "nelson40@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Dennis",
            "last_name": "Santana",
            "username": "santana77",
            "email": "santana77@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Blake",
            "last_name": "Treinen",
            "username": "treinen49",
            "email": "treinen49@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Julio",
            "last_name": "Urias",
            "username": "elculichi",
            "email": "elculichi7@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Austin",
            "last_name": "Barnes",
            "username": "sammy15",
            "email": "sammy15@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Gavin",
            "last_name": "Lux",
            "username": "gavin9",
            "email": "gavin9@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Zach",
            "last_name": "McKinstry",
            "username": "mckinstry",
            "email": "mckinstry8@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Edwin",
            "last_name": "Rios",
            "username": "rios43",
            "email": "rios43@dodgers.com",
            "password": "password",
        },
        {
            "first_name": "Mookie",
            "last_name": "Betts",
            "username": "mookie50",
            "email": "mookie50@dodgers.com",
            "password": "password",
        },

    ]

    for player in players:
        p = User(first_name=player["first_name"],
                 last_name=player["last_name"],
                 username=player["username"],
                 email=player["email"],
                 password=player["password"],
                 )
        db.session.add(p)
        db.session.commit()
