"""empty message

Revision ID: 6bea1b36f3c9
Revises: 
Create Date: 2021-06-22 20:02:30.602337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bea1b36f3c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mlb_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('stadium', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('league', sa.String(length=30), nullable=False),
    sa.Column('division', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stadium')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_player_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('team_abbrev', sa.String(length=10), nullable=True),
    sa.Column('a', sa.String(length=10), nullable=True),
    sa.Column('ab', sa.String(length=10), nullable=True),
    sa.Column('ao', sa.String(length=10), nullable=True),
    sa.Column('avg', sa.String(length=10), nullable=True),
    sa.Column('babip', sa.String(length=10), nullable=True),
    sa.Column('bb', sa.String(length=10), nullable=True),
    sa.Column('bb9', sa.String(length=10), nullable=True),
    sa.Column('bk', sa.String(length=10), nullable=True),
    sa.Column('cg', sa.String(length=10), nullable=True),
    sa.Column('cs', sa.String(length=10), nullable=True),
    sa.Column('cspct', sa.String(length=10), nullable=True),
    sa.Column('d', sa.String(length=10), nullable=True),
    sa.Column('dp', sa.String(length=10), nullable=True),
    sa.Column('e', sa.String(length=10), nullable=True),
    sa.Column('er', sa.String(length=10), nullable=True),
    sa.Column('era', sa.String(length=10), nullable=True),
    sa.Column('fpct', sa.String(length=10), nullable=True),
    sa.Column('g', sa.String(length=10), nullable=True),
    sa.Column('gf', sa.String(length=10), nullable=True),
    sa.Column('gidp', sa.String(length=10), nullable=True),
    sa.Column('go', sa.String(length=10), nullable=True),
    sa.Column('go_ao', sa.String(length=10), nullable=True),
    sa.Column('gs', sa.String(length=10), nullable=True),
    sa.Column('gsh', sa.String(length=10), nullable=True),
    sa.Column('h', sa.String(length=10), nullable=True),
    sa.Column('h9', sa.String(length=10), nullable=True),
    sa.Column('hb', sa.String(length=10), nullable=True),
    sa.Column('hbp', sa.String(length=10), nullable=True),
    sa.Column('hld', sa.String(length=10), nullable=True),
    sa.Column('hr', sa.String(length=10), nullable=True),
    sa.Column('hr9', sa.String(length=10), nullable=True),
    sa.Column('ibb', sa.String(length=10), nullable=True),
    sa.Column('inn', sa.String(length=10), nullable=True),
    sa.Column('ir', sa.String(length=10), nullable=True),
    sa.Column('irs', sa.String(length=10), nullable=True),
    sa.Column('k', sa.String(length=10), nullable=True),
    sa.Column('k9', sa.String(length=10), nullable=True),
    sa.Column('kbb', sa.String(length=10), nullable=True),
    sa.Column('l', sa.String(length=10), nullable=True),
    sa.Column('lob', sa.String(length=10), nullable=True),
    sa.Column('np', sa.String(length=10), nullable=True),
    sa.Column('o', sa.String(length=10), nullable=True),
    sa.Column('obp', sa.String(length=10), nullable=True),
    sa.Column('ofa', sa.String(length=10), nullable=True),
    sa.Column('ops', sa.String(length=10), nullable=True),
    sa.Column('pa', sa.String(length=10), nullable=True),
    sa.Column('pb', sa.String(length=10), nullable=True),
    sa.Column('pip', sa.String(length=10), nullable=True),
    sa.Column('po', sa.String(length=10), nullable=True),
    sa.Column('qs', sa.String(length=10), nullable=True),
    sa.Column('r', sa.String(length=10), nullable=True),
    sa.Column('roe', sa.String(length=10), nullable=True),
    sa.Column('rbi', sa.String(length=10), nullable=True),
    sa.Column('rs9', sa.String(length=10), nullable=True),
    sa.Column('s', sa.String(length=10), nullable=True),
    sa.Column('sb', sa.String(length=10), nullable=True),
    sa.Column('sbpct', sa.String(length=10), nullable=True),
    sa.Column('sf', sa.String(length=10), nullable=True),
    sa.Column('sh', sa.String(length=10), nullable=True),
    sa.Column('sho', sa.String(length=10), nullable=True),
    sa.Column('slg', sa.String(length=10), nullable=True),
    sa.Column('so', sa.String(length=10), nullable=True),
    sa.Column('sv', sa.String(length=10), nullable=True),
    sa.Column('svo', sa.String(length=10), nullable=True),
    sa.Column('svpct', sa.String(length=10), nullable=True),
    sa.Column('t', sa.String(length=10), nullable=True),
    sa.Column('tb', sa.String(length=10), nullable=True),
    sa.Column('tbf', sa.String(length=10), nullable=True),
    sa.Column('tc', sa.String(length=10), nullable=True),
    sa.Column('tp', sa.String(length=10), nullable=True),
    sa.Column('tpa', sa.String(length=10), nullable=True),
    sa.Column('w', sa.String(length=10), nullable=True),
    sa.Column('whip', sa.String(length=10), nullable=True),
    sa.Column('wo', sa.String(length=10), nullable=True),
    sa.Column('wp', sa.String(length=10), nullable=True),
    sa.Column('wpct', sa.String(length=10), nullable=True),
    sa.Column('xbh', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.String(length=30), nullable=False),
    sa.Column('bats', sa.String(length=30), nullable=False),
    sa.Column('birth_date', sa.String(length=30), nullable=False),
    sa.Column('height', sa.String(length=30), nullable=False),
    sa.Column('height_feet', sa.String(length=30), nullable=False),
    sa.Column('height_inches', sa.String(length=30), nullable=False),
    sa.Column('jersey_number', sa.String(length=30), nullable=False),
    sa.Column('mlb_player_id', sa.String(length=30), nullable=False),
    sa.Column('mlb_team_name', sa.String(length=50), nullable=False),
    sa.Column('nick_name', sa.String(length=30), nullable=False),
    sa.Column('primary_position', sa.String(length=30), nullable=False),
    sa.Column('primary_position_txt', sa.String(length=30), nullable=False),
    sa.Column('primary_stat_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('team_abbrev', sa.String(length=30), nullable=False),
    sa.Column('throws', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passcode', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('league_type', sa.String(length=30), nullable=False),
    sa.Column('permissions', sa.String(length=50), nullable=False),
    sa.Column('draft_type', sa.String(length=30), nullable=False),
    sa.Column('draft_date', sa.String(length=30), nullable=False),
    sa.Column('draft_time', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_team_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_player_id', sa.String(length=30), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_team_players')
    op.drop_table('teams')
    op.drop_table('leagues')
    op.drop_table('users')
    op.drop_table('players')
    op.drop_table('player_stats')
    op.drop_table('mlb_teams')
    # ### end Alembic commands ###
